### PR TITLE
docs: add `maxDepth` to templates

### PR DESCRIPTION
**Pull request by shortcuts**
## Summary

https://algolia.atlassian.net/browse/CRAW-2430

Adds the `maxDepth` parameter to the recommended templates.

### CODE REVIEW

**Review by millotp — APPROVED** [review]
Are we sure this will work for all config ? Otherwise good idea

**Comment by shortcuts** [comment]
> Are we sure this will work for all config ? Otherwise good idea

10 is already pretty big for documentations, would you see it higher? The good point is also that it provides a clear `url_too_deep` error which can be easily identifiable for a user

**Comment by millotp** [comment]
For documentation site it makes sense, maybe we can add a link to the [doc](https://www.algolia.com/doc/tools/crawler/apis/configuration/max-depth/) or the error when it happens, so they know which property to change

**Comment by shortcuts** [comment]
> For documentation site it makes sense, maybe we can add a link to the [doc](https://www.algolia.com/doc/tools/crawler/apis/configuration/max-depth/) or the error when it happens, so they know which property to change

On the DocSearch side? It make sense! Would you be able to provide a PR with what you have in mind and put it on this page? https://docsearch.algolia.com/docs/templates

**Pull request merged**
