### PR TITLE
Feat/jsbeautify

### PR DESCRIPTION
**Pull request by s-pace**
Adding js-beautify to format scss file

It will only impact the `./src`folder

New command:
`npm run beautify:scss`

### CODE REVIEW

**Comment by s-pace** [comment]
Let's avoid this PR since it breaks variables with - in their name

**Comment by Haroenv** [comment]
prettier works for css as well, you can use that instead

**Comment by pixelastic** [comment]
@Haroenv does it work with SCSS as well?

**Comment by Haroenv** [comment]
yes

**Comment by pixelastic** [comment]
@s-pace that might me something to look at: having prettier run on both our CSS and JS codebase.

**Comment by Haroenv** [comment]
https://github.com/yarnpkg/website/blob/master/package.json#L27, here's the example

**Comment by pixelastic** [comment]
@Haroenv The command you linked is `yarn prettier --write '**/*.{js,md,scss}'`, how is that different from `prettier --write '**/*.{js,md,scss}'` (minus the `yarn` in front)? It will be run as an `npm`/`yarn` script anyway so `prettier` will be in the `$PATH` already, right?

**Pull request closed without merging**
