### PR TITLE
Bump Jekyll to latest

### PR DESCRIPTION
**Pull request by DirtyF**
👋  Algolians,

This PR updates Jekyll to its latest version. I don't see any rendering error but as I don't know why you are still using Jekyll 2.x maybe I missed something. I just updated the syntax highlighter option to `coderay` as previously.

Congrats on the new design ❤️ 

showcase-docsearch

Happy Jekyllin'!

### CODE REVIEW

**Comment by vvo** [comment]
Nice! Just merged master with the new design, can you check if everything goes well? Gonna add protected branch with update on master button

**Comment by vvo** [comment]
Seems like this works perfectly

**Comment by DirtyF** [comment]
Please note that [coderay is deprecated](https://kramdown.gettalong.org/syntax_highlighter/coderay.html) and that you are encouraged to switch to Rouge (Jekyll's default)

**Comment by vvo** [comment]
> I don't know why you are still using Jekyll 2.x maybe I missed something

Legacy, no particular will. Nowadays we mostly use metalsmith also

**Comment by vvo** [comment]
Sorry there's a conflict now, dunno how to solve it well though

**Comment by vvo** [comment]
Did you check npm run dev:docs works?

**Comment by DirtyF** [comment]
@vvo found in the typo in the script, it's workin' now. 🙌 

Didn't change the highlighter to Rouge as it would change the current style.
Also fixed a minor warning in a Liquid template.

**Comment by DirtyF** [comment]
Already featured in https://www.thenewdynamic.org/showcase/docsearch/ 😉

**Comment by vvo** [comment]
> @vvo found a typo in the script, it's workin' now. 🙌

My bad :)

**Comment by vvo** [comment]
Thanks a lot @DirtyF for awesome contribution :)

**Pull request merged**
