### PR TITLE
Feat/design

### PR DESCRIPTION
**Pull request by LukyVj**
**Summary**

**Result**

### CODE REVIEW

**Comment by redox** [comment]
Should we merge & deploy that @maxiloc @LukyVj ?

**Comment by LukyVj** [comment]
Yes! I I just finished a small commit, gimme 5 and I merge this! I'll let youhandle the deploy.

**Comment by vvo** [comment]
I did a merge master in here, waiting for it to be available, github is having issues right now

**Comment by Haroenv** [comment]
Travis fails because of the commit messages, netlify fails because something on css

```
http://rubydoc.info/github/haml/haml/file/CHANGELOG.md
8:43:31 AM: Configuration file: /opt/build/repo/docs/_config.yml
8:43:31 AM:             Source: /opt/build/repo/docs
       Destination: _site/docsearch
      Generating...
8:43:32 AM:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
8:43:32 AM:                     File to import not found or unreadable: ../node_modules/algolia-frontend-components/components/communityHeader/communityHeader.scss. Load path: /opt/build/repo/docs/css on line 1
8:43:32 AM: jekyll 2.5.3 | Error:  File to import not found or unreadable: ../node_modules/algolia-frontend-components/components/communityHeader/communityHeader.scss.
Load path: /opt/build/repo/docs/css on line 1
8:43:32 AM: Saved Yarn cache
8:43:32 AM: Build complete: exit code: 1
8:43:32 AM: Cleaning up docker container
8:43:32 AM: Error running command: Build script returned non-zero exit code: 1
8:43:32 AM: An error occurred while building the site, skipping the deploy and cache refresh.
8:43:33 AM: Build script returned non-zero exit code: 1
8:43:35 AM: Finished processing build request in 2m30.466416647s
```

**Comment by vvo** [comment]
I notified @s-pace that we can remove the commit message checks and be careful when merging

**Comment by vvo** [comment]
Just found out the issue, thx @Haroenv

**Comment by vvo** [comment]
new design is up

**Comment by DirtyF** [comment]
The og;image: / twitter card does not reflect the current design and use the previous logo: https://twitter.com/jamstatic_fr/status/920591477390151680

**Pull request merged**
