### PR TITLE
feat: add keypress effect to DocSearchButton

### PR DESCRIPTION
**Pull request by SevenOutman**
Add this subtle effect that responds to keypress on <kbd>Meta</kbd>/<kbd>Ctrl</kbd> and <kbd>K</kbd>.

https://github.com/algolia/docsearch/assets/8225666/c35e4c9f-7295-44d4-b258-51250ea4c0e7

https://github.com/algolia/docsearch/assets/8225666/00299419-9bf2-46e1-9f49-105e9d32089c

### CODE REVIEW

**Comment by 8bittitan** [comment]
Hi @SevenOutman this looks really good! Could you please run `yarn test:size` in your local and update the `bundlesize.config.json` accordingly for the CI to pass please? 😄

**Comment by SevenOutman** [comment]
> Hi @SevenOutman this looks really good! Could you please run `yarn test:size` in your local and update the `bundlesize.config.json` accordingly for the CI to pass please? 😄 

Sure. Will do that after coming back from vacation.

**Comment by 8bittitan** [comment]
> > Hi @SevenOutman this looks really good! Could you please run `yarn test:size` in your local and update the `bundlesize.config.json` accordingly for the CI to pass please? 😄
> 
> Sure. Will do that after coming back from vacation.

Ah no worries then, I can take care of it for you! And merge this in after 😄

**Comment by SevenOutman** [comment]
> Ah no worries then, I can take care of it for you! And merge this in after 😄 

That's so helpful. Thanks!

**Pull request merged**
