### PR TITLE
move community website to middleman

### PR DESCRIPTION
**Pull request by maxiloc**

### CODE REVIEW

**Comment by vvo** [comment]
Website seems a bit broken versus the online one.

image

image

**Comment by maxiloc** [comment]
yes it's not finished 😄

**Comment by vvo** [comment]
Need help finishing this?

**Comment by vvo** [comment]
cc @maximloc

**Comment by maxiloc** [comment]
I didn't have time to get to that, if you do: sure 😄 . Most of the work is done, it's all about fixing the last design issues

**Comment by s-pace** [comment]
LGTM

**Pull request merged**
