### PR TITLE
fix(css): Generate `docsearch.css` instead of `docsearch.js.css`

### PR DESCRIPTION
**Pull request by pixelastic**

### CODE REVIEW

**Comment by redox** [comment]
@pixelastic rebase?

**Comment by pixelastic** [comment]
Hmm. I rebased on develop, then force pushed to update the PR, and it got automatically merged.

**Comment by vvo** [comment]
I had done the modification also so it might be that rebasing the PR made your commit already present

**Comment by pixelastic** [comment]
I still had to fix conflicts on my side. But I don't get why the PR got accepted in the end.

No big deal, that's what I wanted, but I'm unsure how GitHub managed to read my mind ;)

**Comment by vvo** [comment]
If all your commits changed lines that were already OK then there was nothing to be done, thus merged (maybe)

**Pull request closed without merging**
