### PR TITLE
fix(input): Throw errors if not exactly one input matching

### LINKED ISSUE #74: Does nothing if inputSelector finds 2 or more tags
If there is in the page 2 or more selectors that matches `inputSelector` it does nothing.

### PR DESCRIPTION
**Pull request by pixelastic**
Fixes #74

### CODE REVIEW

**Comment by redox** [comment]
I think we should rather rely on the latest (not deployed yet) version of `autocomplete.js` to handle multiple search bars. Not throwing anything to keep it jquery-style: `$('.whatever').show().hide().doesntthrow()`

**Comment by pixelastic** [comment]
@redox: Is the new version you're talking about now deployed?

I did not get the `$('.whatever').show().hide().doesntthrow()` part

**Comment by redox** [comment]
About to release it.

**Comment by redox** [comment]
By upgrading to `autocomplete.js=0.17.2` we're now able to bind the dropdown menu to several inputs, like it was already for jquery. Closing this PR.

**Pull request closed without merging**
