### PR TITLE
s/Search in the doc/Search the docs

### PR DESCRIPTION
**Pull request by dzello**
Minor copy update in the DocSearch site search and for the default placeholder on participating sites.

### CODE REVIEW

**Comment by dzello** [comment]
How do I convince travis that `$TRAVIS_BRANCH` is in fact `develop`? :)

**Comment by vvo** [comment]
Thx, The way we contribute to those repos is to open a PR from a feature branch to the develop branch.

So you start from develop, create a new branch then open the PR with the base being develop.

Thx still :)

**Comment by vvo** [comment]
https://github.com/algolia/docsearch/blob/master/CONTRIBUTING.md but it's not really practical. Making develop the default branch should help maybe

**Comment by dzello** [comment]
Oops, should have read the manual :) Got it for next time. +1 to making develop the default... at the least it will make someone take a closer look.

**Comment by vvo** [comment]
We did it on other projects, there should be no impact but exposing the develop code more publicly. Which is fine if we release often.

**Pull request merged**
