### PR TITLE
feat: enable `Cmd+K` shortcut when caps lock is on

### PR DESCRIPTION
**Pull request by lex111**
The search shortcut should be work if even caps lock is on

cc @shortcuts

### CODE REVIEW

**Comment by lex111** [comment]
friendly ping for @francoischalifour @shortcuts

**Review by shortcuts — COMMENTED** [review]
Thanks for the PR! It make sense to me, plus it's also how it works for websites that offers command palette (e.g. GitHub).

Would you mind adding a test here? https://github.com/algolia/docsearch/blob/main/cypress/integration/search/actions.spec.ts#L18

**Comment by lex111** [comment]
Oh yes, just added them.

**Comment by shortcuts** [comment]
> Oh yes, just added them.

Thanks!! Will release the new version on Monday!

**Review by shortcuts — APPROVED** [review]

**Comment by lex111** [comment]
@shortcuts you didn't forget about the new release?

**Comment by shortcuts** [comment]
> @shortcuts you didn't forget about the new release?

image

.... no @lex111

**Pull request merged**
