### PR TITLE
fix(handleSelected): ensure we're calling setVal on the right object

### LINKED ISSUE #51: Click on a suggestion doesn't work
Throws a `Cannot read property 'setVal' of undefined`.

### PR DESCRIPTION
**Pull request by redox**
Fix #51

### CODE REVIEW

**Comment by bobylito** [comment]
LGTM

**Comment by pixelastic** [comment]
Care to add the test?

**Comment by redox** [comment]
Yes, I will; not yet sure how easy that will be :)

**Comment by pixelastic** [comment]
It will not :p

**Pull request merged**
