### PR TITLE
feat(a11y): Hide separators to screen readers

### PR DESCRIPTION
**Pull request by kaelig**
This PR makes DocSearch more accessible to screen readers.

### CODE REVIEW

**Comment by kaelig** [comment]
More commits to come - tests in progress.

**Comment by kaelig** [comment]
@vvo @maxiloc looks like this is all that is needed to make DocSearch accessible :)

**Comment by kaelig** [comment]
@vvo @maxiloc any update on when this might get deployed?

**Comment by maxiloc** [comment]
Yes going to work on it early next week when I come back to the office

**Comment by maxiloc** [comment]
@kaelig It now released. I also made the same fix on docsearch v1 so every docsearch out there can get benefit from that 🎉

Thanks again for your work ❤️  ! This is a great addition to docsearch.

**Comment by kaelig** [comment]
That's amazing, let's give it a few days to see how it goes and if everything is fine we can start announcing the update with the article :) thanks for your support!

**Pull request merged**
