### PR TITLE
feat(css): make breakpoint customizable

### LINKED ISSUE #1439: [docsearch-css] Breakpoint is to be customizable
## Describe the problem

Breakpoints are now fixed and not customizable to align with other library, framework, or design systems.

https://github.com/algolia/docsearch/blob/83abe4c120bb7f5ae5bbd6e0faf229873546d768/packages/docsearch-css/src/button.css#L66
https://github.com/algolia/docsearch/blob/83abe4c120bb7f5ae5bbd6e0faf229873546d768/packages/docsearch-css/src/modal.css#L559

## Describe the solution

Use CSS custom properties to set all breakpoint(s) in docsearch-css.

## Alternatives you've considered

As per Apples's products i.e. iPad, we can directly change that with 768px without a custom property.

### PR DESCRIPTION
**Pull request by tnir**
Closes #1439

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey, thanks for the PR!

Could you please update [this sandbox](https://codesandbox.io/s/vanilla-forked-8vqpq9?file=/src/index.css) to see if it properly work? IIRC media queries are not bound to the DOM so can't read `var`s

**Comment by shortcuts** [comment]
> Should I use https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-env-function instead?

I don't see other alternatives to do it, but since media queries are applied on classes, I believe overriding it from your source code should be enough, no?

You can set it to do nothing at `750px` and apply your logic for any `px` you'd like to trigger it

**Comment by tnir** [comment]
Thanks. I just wanted to do it easy to just change the breakpoint:

```html
<style>
:root {
  --docsearch-breakpoint: 768px;
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3.1.1/dist/style.min.css">
```
No bundling, delivery of the library (`@docsearch/css`) is required.

**Comment by shortcuts** [comment]
> Thanks. I just wanted to do it easy to just change the breakpoint:

I believe overriding media queries are working, you need to first import our stylesheet, then yours with your own logic in it

**Comment by tnir** [comment]
Thanks, your solution is perfect! 👑

**Pull request closed without merging**
